### ISSUE TITLE
Where would one get the full Huawei API documentation

### ISSUE THREAD

**Issue by aluRamb0** [HSPDev/Huawei-E5180-API#1]
Been looking at gaining access the some more operations, wanted to find out if you could share some of your documentation or point me in the right direction as i've been searching on the net with no luck. so far i only got to this [site](https://blog.hqcodeshop.fi/serendipity/index.php?REMOTE_ADDR=197.105.6.239&url=archives/259-Huawei-E5186-AJAX-API.html)

**Comment by oddergaard** [comment]
I'm sorry but I've just used Chrome debug tools to watch the AJAX requests and reverse engineer the API from that.

See how to do it here: http://stackoverflow.com/questions/4939172/in-chrome-how-can-i-see-what-ajax-requests-are-being-made

The hard part is the authentication and such, but you should easily be able to extend my code with more functions because I've already coded the auth and such.

Nice website btw. I wish I've had that myself.
